package Licenta.Licenta.Controller;

import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.Map;

@RestController
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping("/api")
@RequiredArgsConstructor
public class CountryController {
    @GetMapping("/countries")
    public List<Map<String, String>> getCountries() {
        return List.of(
                Map.of("cod", "AF", "nume", "Afghanistan"),
                Map.of("cod", "AL", "nume", "Albania"),
                Map.of("cod", "DZ", "nume", "Algeria"),
                Map.of("cod", "AS", "nume", "American Samoa"),
                Map.of("cod", "AD", "nume", "Andorra"),
                Map.of("cod", "AO", "nume", "Angola"),
                Map.of("cod", "AR", "nume", "Argentina"),
                Map.of("cod", "AM", "nume", "Armenia"),
                Map.of("cod", "AU", "nume", "Australia"),
                Map.of("cod", "AT", "nume", "Austria"),
                Map.of("cod", "AZ", "nume", "Azerbaijan"),
                Map.of("cod", "BS", "nume", "Bahamas"),
                Map.of("cod", "BH", "nume", "Bahrain"),
                Map.of("cod", "BD", "nume", "Bangladesh"),
                Map.of("cod", "BB", "nume", "Barbados"),
                Map.of("cod", "BY", "nume", "Belarus"),
                Map.of("cod", "BE", "nume", "Belgium"),
                Map.of("cod", "BZ", "nume", "Belize"),
                Map.of("cod", "BJ", "nume", "Benin"),
                Map.of("cod", "BT", "nume", "Bhutan"),
                Map.of("cod", "BO", "nume", "Bolivia"),
                Map.of("cod", "BA", "nume", "Bosnia and Herzegovina"),
                Map.of("cod", "BW", "nume", "Botswana"),
                Map.of("cod", "BR", "nume", "Brazil"),
                Map.of("cod", "BN", "nume", "Brunei"),
                Map.of("cod", "BG", "nume", "Bulgaria"),
                Map.of("cod", "BF", "nume", "Burkina Faso"),
                Map.of("cod", "BI", "nume", "Burundi"),
                Map.of("cod", "CV", "nume", "Cape Verde"),
                Map.of("cod", "KH", "nume", "Cambodia"),
                Map.of("cod", "CM", "nume", "Cameroon"),
                Map.of("cod", "CA", "nume", "Canada"),
                Map.of("cod", "KY", "nume", "Cayman Islands"),
                Map.of("cod", "CF", "nume", "Central African Republic"),
                Map.of("cod", "TD", "nume", "Chad"),
                Map.of("cod", "CL", "nume", "Chile"),
                Map.of("cod", "CN", "nume", "China"),
                Map.of("cod", "CO", "nume", "Colombia"),
                Map.of("cod", "KM", "nume", "Comoros"),
                Map.of("cod", "CG", "nume", "Congo"),
                Map.of("cod", "CD", "nume", "Democratic Republic of the Congo"),
                Map.of("cod", "CR", "nume", "Costa Rica"),
                Map.of("cod", "CI", "nume", "Ivory Coast"),
                Map.of("cod", "HR", "nume", "Croatia"),
                Map.of("cod", "CU", "nume", "Cuba"),
                Map.of("cod", "CY", "nume", "Cyprus"),
                Map.of("cod", "CZ", "nume", "Czech Republic"),
                Map.of("cod", "DK", "nume", "Denmark"),
                Map.of("cod", "DJ", "nume", "Djibouti"),
                Map.of("cod", "DM", "nume", "Dominica"),
                Map.of("cod", "DO", "nume", "Dominican Republic"),
                Map.of("cod", "EC", "nume", "Ecuador"),
                Map.of("cod", "EG", "nume", "Egypt"),
                Map.of("cod", "SV", "nume", "El Salvador"),
                Map.of("cod", "GQ", "nume", "Equatorial Guinea"),
                Map.of("cod", "ER", "nume", "Eritrea"),
                Map.of("cod", "EE", "nume", "Estonia"),
                Map.of("cod", "SZ", "nume", "Eswatini"),
                Map.of("cod", "ET", "nume", "Ethiopia"),
                Map.of("cod", "FJ", "nume", "Fiji"),
                Map.of("cod", "FI", "nume", "Finland"),
                Map.of("cod", "FR", "nume", "France"),
                Map.of("cod", "GA", "nume", "Gabon"),
                Map.of("cod", "GM", "nume", "Gambia"),
                Map.of("cod", "GE", "nume", "Georgia"),
                Map.of("cod", "DE", "nume", "Germany"),
                Map.of("cod", "GH", "nume", "Ghana"),
                Map.of("cod", "GR", "nume", "Greece"),
                Map.of("cod", "GD", "nume", "Grenada"),
                Map.of("cod", "GT", "nume", "Guatemala"),
                Map.of("cod", "GN", "nume", "Guinea"),
                Map.of("cod", "GW", "nume", "Guinea-Bissau"),
                Map.of("cod", "GY", "nume", "Guyana"),
                Map.of("cod", "HT", "nume", "Haiti"),
                Map.of("cod", "HN", "nume", "Honduras"),
                Map.of("cod", "HU", "nume", "Hungary"),
                Map.of("cod", "IS", "nume", "Iceland"),
                Map.of("cod", "IN", "nume", "India"),
                Map.of("cod", "ID", "nume", "Indonesia"),
                Map.of("cod", "IR", "nume", "Iran"),
                Map.of("cod", "IQ", "nume", "Iraq"),
                Map.of("cod", "IE", "nume", "Ireland"),
                Map.of("cod", "IL", "nume", "Israel"),
                Map.of("cod", "IT", "nume", "Italy"),
                Map.of("cod", "JM", "nume", "Jamaica"),
                Map.of("cod", "JP", "nume", "Japan"),
                Map.of("cod", "JO", "nume", "Jordan"),
                Map.of("cod", "KZ", "nume", "Kazakhstan"),
                Map.of("cod", "KE", "nume", "Kenya"),
                Map.of("cod", "KI", "nume", "Kiribati"),
                Map.of("cod", "KW", "nume", "Kuwait"),
                Map.of("cod", "KG", "nume", "Kyrgyzstan"),
                Map.of("cod", "LA", "nume", "Laos"),
                Map.of("cod", "LV", "nume", "Latvia"),
                Map.of("cod", "LB", "nume", "Lebanon"),
                Map.of("cod", "LS", "nume", "Lesotho"),
                Map.of("cod", "LR", "nume", "Liberia"),
                Map.of("cod", "LY", "nume", "Libya"),
                Map.of("cod", "LI", "nume", "Liechtenstein"),
                Map.of("cod", "LT", "nume", "Lithuania"),
                Map.of("cod", "LU", "nume", "Luxembourg"),
                Map.of("cod", "MG", "nume", "Madagascar"),
                Map.of("cod", "MW", "nume", "Malawi"),
                Map.of("cod", "MY", "nume", "Malaysia"),
                Map.of("cod", "MV", "nume", "Maldives"),
                Map.of("cod", "ML", "nume", "Mali"),
                Map.of("cod", "MT", "nume", "Malta"),
                Map.of("cod", "MH", "nume", "Marshall Islands"),
                Map.of("cod", "MQ", "nume", "Martinique"),
                Map.of("cod", "MR", "nume", "Mauritania"),
                Map.of("cod", "MU", "nume", "Mauritius"),
                Map.of("cod", "MX", "nume", "Mexico"),
                Map.of("cod", "FM", "nume", "Micronesia"),
                Map.of("cod", "MD", "nume", "Moldova"),
                Map.of("cod", "MC", "nume", "Monaco"),
                Map.of("cod", "MN", "nume", "Mongolia"),
                Map.of("cod", "ME", "nume", "Montenegro"),
                Map.of("cod", "MA", "nume", "Morocco"),
                Map.of("cod", "MZ", "nume", "Mozambique"),
                Map.of("cod", "MM", "nume", "Myanmar"),
                Map.of("cod", "NA", "nume", "Namibia"),
                Map.of("cod", "NR", "nume", "Nauru"),
                Map.of("cod", "NP", "nume", "Nepal"),
                Map.of("cod", "NL", "nume", "Netherlands"),
                Map.of("cod", "NC", "nume", "New Caledonia"),
                Map.of("cod", "NZ", "nume", "New Zealand"),
                Map.of("cod", "NI", "nume", "Nicaragua"),
                Map.of("cod", "NE", "nume", "Niger"),
                Map.of("cod", "NG", "nume", "Nigeria"),
                Map.of("cod", "NO", "nume", "Norway"),
                Map.of("cod", "OM", "nume", "Oman"),
                Map.of("cod", "PK", "nume", "Pakistan"),
                Map.of("cod", "PW", "nume", "Palau"),
                Map.of("cod", "PA", "nume", "Panama"),
                Map.of("cod", "PG", "nume", "Papua New Guinea"),
                Map.of("cod", "PY", "nume", "Paraguay"),
                Map.of("cod", "PE", "nume", "Peru"),
                Map.of("cod", "PH", "nume", "Philippines"),
                Map.of("cod", "PL", "nume", "Poland"),
                Map.of("cod", "PT", "nume", "Portugal"),
                Map.of("cod", "QA", "nume", "Qatar"),
                Map.of("cod", "RO", "nume", "Romania"),
                Map.of("cod", "RU", "nume", "Russia"),
                Map.of("cod", "RW", "nume", "Rwanda"),
                Map.of("cod", "ST", "nume", "São Tomé and Príncipe"),
                Map.of("cod", "SA", "nume", "Saudi Arabia"),
                Map.of("cod", "SN", "nume", "Senegal"),
                Map.of("cod", "RS", "nume", "Serbia"),
                Map.of("cod", "SC", "nume", "Seychelles"),
                Map.of("cod", "SL", "nume", "Sierra Leone"),
                Map.of("cod", "SG", "nume", "Singapore"),
                Map.of("cod", "SK", "nume", "Slovakia"),
                Map.of("cod", "SI", "nume", "Slovenia"),
                Map.of("cod", "SB", "nume", "Solomon Islands"),
                Map.of("cod", "SO", "nume", "Somalia"),
                Map.of("cod", "ZA", "nume", "South Africa"),
                Map.of("cod", "SS", "nume", "South Sudan"),
                Map.of("cod", "ES", "nume", "Spain"),
                Map.of("cod", "LK", "nume", "Sri Lanka"),
                Map.of("cod", "SD", "nume", "Sudan"),
                Map.of("cod", "SR", "nume", "Suriname"),
                Map.of("cod", "SE", "nume", "Sweden"),
                Map.of("cod", "CH", "nume", "Switzerland"),
                Map.of("cod", "SY", "nume", "Syria"),
                Map.of("cod", "TW", "nume", "Taiwan"),
                Map.of("cod", "TJ", "nume", "Tajikistan"),
                Map.of("cod", "TZ", "nume", "Tanzania"),
                Map.of("cod", "TH", "nume", "Thailand"),
                Map.of("cod", "TL", "nume", "Timor-Leste"),
                Map.of("cod", "TG", "nume", "Togo"),
                Map.of("cod", "TO", "nume", "Tonga"),
                Map.of("cod", "TT", "nume", "Trinidad and Tobago"),
                Map.of("cod", "TN", "nume", "Tunisia"),
                Map.of("cod", "TR", "nume", "Turkey"),
                Map.of("cod", "TM", "nume", "Turkmenistan"),
                Map.of("cod", "UG", "nume", "Uganda"),
                Map.of("cod", "UA", "nume", "Ukraine"),
                Map.of("cod", "AE", "nume", "United Arab Emirates"),
                Map.of("cod", "GB", "nume", "United Kingdom"),
                Map.of("cod", "US", "nume", "United States"),
                Map.of("cod", "UY", "nume", "Uruguay"),
                Map.of("cod", "UZ", "nume", "Uzbekistan"),
                Map.of("cod", "VU", "nume", "Vanuatu"),
                Map.of("cod", "VE", "nume", "Venezuela"),
                Map.of("cod", "VN", "nume", "Vietnam"),
                Map.of("cod", "YE", "nume", "Yemen"),
                Map.of("cod", "ZM", "nume", "Zambia"),
                Map.of("cod", "ZW", "nume", "Zimbabwe")
        );

    }
}